# Generated by Django 2.0.6 on 2018-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Compentency',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='competency',
            name='experience',
            field=models.ForeignKey(on_delete=models.SET('Less than two years'), to='starlight.Experience'),
        ),
        migrations.AddField(
            model_name='competency',
            name='interest',
            field=models.ForeignKey(on_delete=models.SET('Not interested'), to='starlight.Interest'),
        ),
        migrations.AddField(
            model_name='employee',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='employees', to='starlight.Competency'),
        ),
    ]
