# Generated by Django 2.0.6 on 2018-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'verbose_name_plural': 'competencies'},
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=150, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='test', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
