# Generated by Django 2.0.7 on 2018-07-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starlight', '0002_auto_20180705_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ['skill'], 'verbose_name_plural': 'competencies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
