# Generated by Django 2.0.6 on 2018-06-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starlight', '0002_auto_20180605_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_technical', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competency',
            name='name',
        ),
        migrations.AlterField(
            model_name='competency',
            name='experience',
            field=models.CharField(choices=[('0-2', 'Less than two years'), ('2-4', 'Two to four years'), ('4-6', 'Four to six years'), ('6-10', 'Six to ten years'), ('10+', 'More than ten years')], max_length=50),
        ),
        migrations.AlterField(
            model_name='competency',
            name='interest',
            field=models.CharField(choices=[('1', 'Not interested'), ('2', 'Interested to learn'), ('3', 'Competent'), ('4', 'Can share knowledge')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='competency',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starlight.Skill'),
        ),
    ]
